toc:
  - name: Neos.js Library
    description: |
      This is the Neos.js library for interfacing with NeosVR
    children:
      - Neos.js
  - Neos
  - name: CloudX
    description: |
      Supporting Documentation for Neos.js
      Docs are still being Created, And will likely be a mess for now

      Children: {[Shared](#shared),[Util](#util)}
  - name: Shared
    description: |
      Core NeosVR API

      [CloudX.Shared](#shared)

      Properties Listed Below
  - AccountType
  - AssetDiff
  - AssetEntry
  - AssetInfo
  - AssetMetadataRequest
  - AssetUploadData
  - CloudXInterface
  - User
  - name: Util
    description: |
      Supporting Classes and Types

      [CloudX.Util](#util)

      Properties Listed Below
  - Char
  - Dictionary
  - Enumerable
  - HashSet
  - List
  - Out
  - StringBuilder
  - Uri
  - name: Arguments
    description: |
      Special Argument Type Definitions. These do not have Classes and are included solely for Typing and Descriptions.
    children:
      - AssetDiffEnum
      - NeosGeneratorOptions
  - name: Uncategorized
    description: |
      None of these have been categorized yet. WIP
      Want to contribute? [Contributing Guide](https://github.com/PolyLogiX-Studio/Neos.js/blob/master/.github/CONTRIBUTING.md)
