language: node_js
node_js:
  - node
  - 12
os: linux

script: 
  - echo "Running tests against $(node -v) ..."
  - npm run lint
  - npm run test

notifications: 
  email: false

jobs:
  include:
    - stage: compile
      script: npm run lint
    - stage: test
      script: 
        - echo "Running tests against $(node -v) ..."
        - npm run test
    - stage: deploy
      script: npx semantic-release
stages:
  - compile
  - test
  - deploy