language: node_js
node_js:
  - node
os: linux

notifications:
  email: false

jobs:
  include:
    - stage: compile
      script: npm run lint
    - stage: test
      script: npm run test
stages:
  - compile
  - test
