name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Be sure to check the active issues to see that your issue has not already been posted."
          pr-message: "Make sure to follow our Contributing guide!"
